#lang racket

;; Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

;; By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


(define (fib n)
  (if (< n 2) 1 (+ (fib (- n 1)) (fib (- n 2)))))

(map fib (list 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15))
